### ISSUE TITLE
Tab errors when running python setup.py install

### ISSUE THREAD

**Issue by julienchastang** [suvarchal/JyIDV#7]
When running

`python setup.py install`

getting

`Sorry: TabError: inconsistent use of tabs and spaces in indentation (jyidv_kernel.py,line 75)`

**Comment by suvarchal** [comment]
is it python 3? 
mine runs clean like this.....

> running install
> running build
> running build_py
> creating build
> creating build/lib
> copying jyidv_kernel.py -> build/lib
> running install_lib
> copying build/lib/jyidv_kernel.py -> /home/suvarchal/miniconda/lib/python2.7/site-packages
> byte-compiling /home/suvarchal/miniconda/lib/python2.7/site-packages/jyidv_kernel.py to jyidv_kernel.pyc
> running install_egg_info
> running egg_info
> creating jyidv_kernel.egg-info
> writing requirements to jyidv_kernel.egg-info/requires.txt
> writing jyidv_kernel.egg-info/PKG-INFO
> writing top-level names to jyidv_kernel.egg-info/top_level.txt
> writing dependency_links to jyidv_kernel.egg-info/dependency_links.txt
> writing pbr to jyidv_kernel.egg-info/pbr.json
> writing manifest file 'jyidv_kernel.egg-info/SOURCES.txt'
> reading manifest file 'jyidv_kernel.egg-info/SOURCES.txt'
> writing manifest file 'jyidv_kernel.egg-info/SOURCES.txt'
> removing '/home/suvarchal/miniconda/lib/python2.7/site-packages/jyidv_kernel-0.9.1-py2.7.egg-info' (and everything under it)
> Copying jyidv_kernel.egg-info to /home/suvarchal/miniconda/lib/python2.7/site-packages/jyidv_kernel-0.9.1-py2.7.egg-info
> Installing kernel spec

**Comment by suvarchal** [comment]
Interesting! after installing pylint, I got the same error probably something with how setuptools work while pylint is installed.

Fixed the errors.
